name: Versioned Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Initial version'
        required: true
        default: '8.0.95'  # Set your initial version here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Latest Tag
        id: version
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0 || echo ${{ github.event.inputs.version }})"

      - name: Get Previous Build Number
        id: previous_build
        run: echo "::set-output name=build_number::${{ github.run_id }}"

      - name: Increment Build Number
        id: build
        run: echo "::set-output name=build_number::${{ steps.previous_build.outputs.build_number + 1 }}"

      - name: Set Tag
        run: git tag ${{ steps.version.outputs.version }}.${{ steps.build.outputs.build_number }}

      - name: Push Tag
        run: git push origin ${{ steps.version.outputs.version }}.${{ steps.build.outputs.build_number }}
