name: Versioned Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Initial version'
        required: true
        default: '8.0.95'  # Set your initial version here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Get Last Build Number
        id: version
        run: echo "::set-output name=build_number::$(($(git tag -l "${{ env.VERSION }}.*" | cut -d '.' -f 3 | sort -n | tail -n 1) + 1))"

      - name: Get Version and Build Number
        run: |
          echo "Version: ${{ env.VERSION }}"
          echo "Build Number: ${{ steps.version.outputs.build_number }}"

      - name: Set Tag
        run: |
          echo "::set-output name=tag::${{ env.VERSION }}.${{ steps.version.outputs.build_number }}"
          echo "Setting tag as ${{ env.VERSION }}.${{ steps.version.outputs.build_number }}"
