name: Versioned Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Initial version'
        required: true
        default: '8.0.95'  # Set your initial version here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Get Version and Build Number
        run: |
          echo "Version: ${{ env.VERSION }}"
          echo "Build Number: ${{ env.BUILD_NUMBER }}"

      - name: Set Tag
        run: |
          echo "::set-output name=tag::${{ env.VERSION }}.${{ env.BUILD_NUMBER }}"
          echo "Setting tag as ${{ env.VERSION }}.${{ env.BUILD_NUMBER }}"
