name: BuildSprint96

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Initial version'
        required: true
        default: '8.0.96'  # Set your initial version here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Set Tag
        id: version
        run: |
          echo "::set-output name=tag::${{ env.VERSION }}"
          echo "Setting tag as ${{ env.VERSION }}"

      - name: Push Tag
        run: |
         tag_name="${{ steps.version.outputs.tag }}"
         git tag -a $tag_name -m "Release $tag_name"
         git push origin $tag_name

